### ISSUE TITLE
polaris-server crash when register api

### ISSUE THREAD

**Issue by chenyukang** [polarismesh/polaris#116]
**Describe the bug**
Follow the steps in polaris-go, polaris-server will crash 

**To Reproduce**
Steps to reproduce the behavior.

All the configuration is default.

Use `install.sh` will also crash the polaris-server, so I tried with commands, when sdk trying to register a new API, it will crash with errors:

```shell
coder@pearl:~/polaris/polaris-standalone-release_v1.2.1.linux.amd64/polaris-server-release_v1.2.1.linux.amd64$ sudo ./polaris-server start
[INFO] load config from polaris-server.yaml
{Bootstrap:{Logger:{OutputPaths:[] ErrorOutputPaths:[] RotateOutputPath:log/polaris-server.log RotationMaxSize:500 RotationMaxAge:30 RotationMaxBackups:100 JSONEncoding:false LogGrpc:false Level:debug outputLevels: logCallers: stackTraceLevels:} StartInOrder:map[key:sz open:true] PolarisService:{EnableRegister:false ProbeAddress: Isolated:false Services:[0xc000067340 0xc000067380]}} APIServers:[{Name:httpserver Option:map[connLimit:map[maxConnLimit:5120 maxConnPerHost:128 openConnLimit:false purgeCounterExpired:5s purgeCounterInterval:10s whiteList:127.0.0.1] enablePprof:true listenIP:0.0.0.0 listenPort:8090] API:map[admin:{Enable:true Include:[]} client:{Enable:true Include:[discover register healthcheck]} console:{Enable:true Include:[default]}]} {Name:grpcserver Option:map[connLimit:map[maxConnLimit:5120 maxConnPerHost:128 openConnLimit:false] listenIP:0.0.0.0 listenPort:8091] API:map[client:{Enable:true Include:[discover register healthcheck]}]}] Cache:{Open:true Resources:[{Name:service Option:map[disableBusiness:false needMeta:true]} {Name:instance Option:map[disableBusiness:false needMeta:true]} {Name:routingConfig Option:map[]} {Name:rateLimitConfig Option:map[]} {Name:circuitBreakerConfig Option:map[]}]} Naming:{Auth:map[open:false] HealthCheck:{Open:true KvConnNum:0 KvServiceName: KvNamespace: KvPasswd: SlotNum:30 LocalHost: MaxIdle:20 IdleTimeout:120} Batch:map[deregister:map[concurrency:64 maxBatchCount:32 open:true queueSize:10240 waitTime:32ms] register:map[concurrency:64 maxBatchCount:32 open:true queueSize:10240 waitTime:32ms]]} Store:{Name:boltdbStore Option:map[path:./polaris.bolt]} Plugin:{CMDB:{Name: Option:map[]} RateLimit:{Name:token-bucket Option:map[api-limit:map[apis:[map[name:POST:/v1/naming/services rule:store-write] map[name:PUT:/v1/naming/services rule:store-write] map[name:POST:/v1/naming/services/delete rule:store-write] map[name:GET:/v1/naming/services rule:store-read] map[name:GET:/v1/naming/services/count rule:store-read] map[name:]] open:false rules:[map[limit:map[bucket:2000 open:true rate:1000] name:store-read] map[limit:map[bucket:1000 open:true rate:500] name:store-write]]] instance-limit:map[global:map[bucket:2 rate:2] open:true resource-cache-amount:1024] ip-limit:map[global:map[bucket:300 open:true rate:200] open:true resource-cache-amount:1024 white-list:[127.0.0.1]] remote-conf:false]} History:{Name:HistoryLogger Option:map[]} Statis:{Name:local Option:map[interval:60 outputPath:./statis]} DiscoverStatis:{Name:discoverLocal Option:map[interval:60 outputPath:./discover-statis]} ParsePassword:{Name: Option:map[]} Auth:{Name: Option:map[]} MeshResourceValidate:{Name: Option:map[]}}}
finish starting server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaababb]

goroutine 41 [running]:
github.com/polarismesh/polaris-server/store/boltdbStore.(*serviceStore).GetSourceServiceToken(0xc0001eab80, 0xc0001e89f0, 0x5, 0xc0001e89f8, 0x4, 0x0, 0x0, 0x0)
        /home/runner/work/polaris/polaris/store/boltdbStore/service.go:181 +0xbb
github.com/polarismesh/polaris-server/naming/batch.(*InstanceCtrl).batchVerifyInstances(0xc0000d4000, 0xc00031ec60, 0xc00031ec60, 0x0, 0x0, 0xc000302e00)
        /home/runner/work/polaris/polaris/naming/batch/instance.go:385 +0x6ce
github.com/polarismesh/polaris-server/naming/batch.(*InstanceCtrl).registerHandler(0xc0000d4000, 0xc0000aa500, 0x1, 0x20, 0xc000067550, 0x10f9001)
        /home/runner/work/polaris/polaris/naming/batch/instance.go:226 +0x2b5
github.com/polarismesh/polaris-server/naming/batch.(*InstanceCtrl).storeWorker(0xc0000d4000, 0xd3f838, 0xc000067540, 0x4)
        /home/runner/work/polaris/polaris/naming/batch/instance.go:181 +0x24b
created by github.com/polarismesh/polaris-server/naming/batch.(*InstanceCtrl).Start
        /home/runner/work/polaris/polaris/naming/batch/instance.go:93 +0x1b5
```

Go code for registering a new API:
```go
func main() {

	provider, err := api.NewProviderAPI()
	if nil != err {
		log.Fatal(err)
	}
	//defer provider.Destroy()

	request := &api.InstanceRegisterRequest{}
	request.Namespace = "Test"
	request.Service = "dummy"
	request.Host = "127.0.0.1"
	request.Port = 8093

	//set the instance ttl, server will set instance 	unhealthy when not receiving heartbeat after 2*ttl
	request.SetTTL(10)

	resp, err := provider.Register(request)
	if nil != err {
		log.Fatal(err)
	}
	log.Println(resp)
}
```

**Expected behavior**
Successfully register a new API.

**Environment**
- Version: 
   `polaris-standalone-release_v1.2.1.linux.amd64`
   `polaris-go v1.0.0`

- OS: 
  `Linux pearl 5.8.0-1041-azure #44~20.04.1-Ubuntu SMP Fri Aug 20 20:41:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
Start with default config file `polaris-server.yaml` in release.

**Comment by chenhengqi** [comment]
Could you please repro this with the latest release ?

**Comment by chenyukang** [comment]
> Could you please repro this with the latest release ?

Update to the latest version of standalone, the `polaris-server` will not crash, but register a new API still failed with error messages: 

```bash
coder@pearl:~/polaris/polaris-go/sample/quickstart/provider$ ./provider --service="web-port" --namespace="default" --host="127.0.0.1" --port=8093
2021/10/08 14:07:45 start to invoke register operation
2021/10/08 14:07:45 fail to register instance, err is Polaris-1006(ErrCodeServerUserError): fail to registerInstance, request {service=web-port, namespace=default, host=127.0.0.1, port=8093}, server code 400202, reason not found resource, server {ID: 2605026103, Address: 127.0.0.1:8091}
```

It's the same result with the commands in sample code: 
https://github.com/polarismesh/polaris-go/tree/main/sample/quickstart/provider
